# Generated by Django 3.0.2 on 2020-01-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(null=True, to='qa.Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='details',
            field=models.CharField(default='', max_length=512),
        ),
    ]
