# Generated by Django 3.0.2 on 2020-01-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20200125_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='details',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
