# Generated by Django 3.0.2 on 2020-01-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20200125_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, to='qa.Answer'),
        ),
    ]
