# Generated by Django 3.0.3 on 2020-02-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_auto_20200203_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAvatar',
        ),
    ]
