# Generated by Django 3.0.3 on 2020-02-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_delete_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(max_length=4096),
        ),
    ]
