# Generated by Django 3.0.3 on 2020-02-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_auto_20200207_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
