# Generated by Django 3.0.3 on 2020-02-14 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0014_answer_upvoters'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='_answer_downvoters_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
