# Generated by Django 3.0.3 on 2020-02-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0015_answer_downvoters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
    ]
