# Generated by Django 3.0.3 on 2020-02-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0016_auto_20200214_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
