# Generated by Django 3.0.3 on 2020-02-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0018_auto_20200214_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-timestamp']},
        ),
    ]
