# Generated by Django 3.0.3 on 2020-02-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0019_auto_20200214_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(to='qa.Topic'),
        ),
    ]
